//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace AvaTax_Calc_DirectSOAP_csharp.AddressService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AddressSvcSoap", Namespace="http://avatax.avalara.com/services")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResult))]
    public partial class AddressSvc : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private Profile profileValueField;
        
        private System.Threading.SendOrPostCallback ValidateOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsAuthorizedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AddressSvc() {
            this.Url = global::AvaTax_Calc_DirectSOAP_csharp.Properties.Settings.Default.AvaTax_Calc_DirectSOAP_csharp_AddressService_AddressSvc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Profile ProfileValue {
            get {
                return this.profileValueField;
            }
            set {
                this.profileValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateCompletedEventHandler ValidateCompleted;
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event IsAuthorizedCompletedEventHandler IsAuthorizedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ProfileValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/Validate", RequestNamespace="http://avatax.avalara.com/services", ResponseNamespace="http://avatax.avalara.com/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ValidateResult Validate(ValidateRequest ValidateRequest) {
            object[] results = this.Invoke("Validate", new object[] {
                        ValidateRequest});
            return ((ValidateResult)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateAsync(ValidateRequest ValidateRequest) {
            this.ValidateAsync(ValidateRequest, null);
        }
        
        /// <remarks/>
        public void ValidateAsync(ValidateRequest ValidateRequest, object userState) {
            if ((this.ValidateOperationCompleted == null)) {
                this.ValidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateOperationCompleted);
            }
            this.InvokeAsync("Validate", new object[] {
                        ValidateRequest}, this.ValidateOperationCompleted, userState);
        }
        
        private void OnValidateOperationCompleted(object arg) {
            if ((this.ValidateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateCompleted(this, new ValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ProfileValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/Ping", RequestNamespace="http://avatax.avalara.com/services", ResponseNamespace="http://avatax.avalara.com/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PingResult Ping(string Message) {
            object[] results = this.Invoke("Ping", new object[] {
                        Message});
            return ((PingResult)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync(string Message) {
            this.PingAsync(Message, null);
        }
        
        /// <remarks/>
        public void PingAsync(string Message, object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[] {
                        Message}, this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ProfileValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/IsAuthorized", RequestNamespace="http://avatax.avalara.com/services", ResponseNamespace="http://avatax.avalara.com/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IsAuthorizedResult IsAuthorized(string Operations) {
            object[] results = this.Invoke("IsAuthorized", new object[] {
                        Operations});
            return ((IsAuthorizedResult)(results[0]));
        }
        
        /// <remarks/>
        public void IsAuthorizedAsync(string Operations) {
            this.IsAuthorizedAsync(Operations, null);
        }
        
        /// <remarks/>
        public void IsAuthorizedAsync(string Operations, object userState) {
            if ((this.IsAuthorizedOperationCompleted == null)) {
                this.IsAuthorizedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsAuthorizedOperationCompleted);
            }
            this.InvokeAsync("IsAuthorized", new object[] {
                        Operations}, this.IsAuthorizedOperationCompleted, userState);
        }
        
        private void OnIsAuthorizedOperationCompleted(object arg) {
            if ((this.IsAuthorizedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsAuthorizedCompleted(this, new IsAuthorizedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://avatax.avalara.com/services", IsNullable=false)]
    public partial class Profile : System.Web.Services.Protocols.SoapHeader {
        
        private string nameField;
        
        private string clientField;
        
        private string adapterField;
        
        private string machineField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public string Adapter {
            get {
                return this.adapterField;
            }
            set {
                this.adapterField = value;
            }
        }
        
        /// <remarks/>
        public string Machine {
            get {
                return this.machineField;
            }
            set {
                this.machineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public partial class Message {
        
        private string summaryField;
        
        private string detailsField;
        
        private string helpLinkField;
        
        private string refersToField;
        
        private SeverityLevel severityField;
        
        private string sourceField;
        
        private string nameField;
        
        /// <remarks/>
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        public string Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public string HelpLink {
            get {
                return this.helpLinkField;
            }
            set {
                this.helpLinkField = value;
            }
        }
        
        /// <remarks/>
        public string RefersTo {
            get {
                return this.refersToField;
            }
            set {
                this.refersToField = value;
            }
        }
        
        /// <remarks/>
        public SeverityLevel Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public enum SeverityLevel {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Exception,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsAuthorizedResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public partial class BaseResult {
        
        private string transactionIdField;
        
        private SeverityLevel resultCodeField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public SeverityLevel ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public partial class IsAuthorizedResult : BaseResult {
        
        private string operationsField;
        
        private System.DateTime expiresField;
        
        /// <remarks/>
        public string Operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public partial class PingResult : BaseResult {
        
        private string versionField;
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public partial class ValidateResult : BaseResult {
        
        private ValidAddress[] validAddressesField;
        
        private bool taxableField;
        
        /// <remarks/>
        public ValidAddress[] ValidAddresses {
            get {
                return this.validAddressesField;
            }
            set {
                this.validAddressesField = value;
            }
        }
        
        /// <remarks/>
        public bool Taxable {
            get {
                return this.taxableField;
            }
            set {
                this.taxableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public partial class ValidAddress : BaseAddress {
        
        private string line4Field;
        
        private string countyField;
        
        private string fipsCodeField;
        
        private string carrierRouteField;
        
        private string postNetField;
        
        private string addressTypeField;
        
        private string validateStatusField;
        
        private string geocodeTypeField;
        
        /// <remarks/>
        public string Line4 {
            get {
                return this.line4Field;
            }
            set {
                this.line4Field = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string FipsCode {
            get {
                return this.fipsCodeField;
            }
            set {
                this.fipsCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
            }
        }
        
        /// <remarks/>
        public string PostNet {
            get {
                return this.postNetField;
            }
            set {
                this.postNetField = value;
            }
        }
        
        /// <remarks/>
        public string AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ValidateStatus {
            get {
                return this.validateStatusField;
            }
            set {
                this.validateStatusField = value;
            }
        }
        
        /// <remarks/>
        public string GeocodeType {
            get {
                return this.geocodeTypeField;
            }
            set {
                this.geocodeTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidAddress))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public partial class BaseAddress {
        
        private string addressCodeField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private string cityField;
        
        private string regionField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private int taxRegionIdField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        /// <remarks/>
        public string AddressCode {
            get {
                return this.addressCodeField;
            }
            set {
                this.addressCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        public string Line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public int TaxRegionId {
            get {
                return this.taxRegionIdField;
            }
            set {
                this.taxRegionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public partial class ValidateRequest {
        
        private BaseAddress addressField;
        
        private TextCase textCaseField;
        
        private bool coordinatesField;
        
        private bool taxabilityField;
        
        private System.DateTime dateField;
        
        /// <remarks/>
        public BaseAddress Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public TextCase TextCase {
            get {
                return this.textCaseField;
            }
            set {
                this.textCaseField = value;
            }
        }
        
        /// <remarks/>
        public bool Coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
        
        /// <remarks/>
        public bool Taxability {
            get {
                return this.taxabilityField;
            }
            set {
                this.taxabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avatax.avalara.com/services")]
    public enum TextCase {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Upper,
        
        /// <remarks/>
        Mixed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ValidateCompletedEventHandler(object sender, ValidateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidateResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidateResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PingResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PingResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void IsAuthorizedCompletedEventHandler(object sender, IsAuthorizedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsAuthorizedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsAuthorizedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IsAuthorizedResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IsAuthorizedResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591